### ISSUE TITLE
Broken build for version 2.3.1

### ISSUE THREAD

**Issue by beiske** [elasticsearch/elasticsearch-lang-python#26]
When trying to install version 2.3.1, which is missing from the docs, but seems to be required for 1.3.5 to 1.3.7 (according to issue #23), I get the following error:

```
+ bin/plugin -install elasticsearch/elasticsearch-lang-python/2.3.1
-> Installing elasticsearch/elasticsearch-lang-python/2.3.1...
Trying http://download.elasticsearch.org/elasticsearch/elasticsearch-lang-python/elasticsearch-lang-python-2.3.1.zip...
Trying http://search.maven.org/remotecontent?filepath=elasticsearch/elasticsearch-lang-python/2.3.1/elasticsearch-lang-python-2.3.1.zip...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/elasticsearch/elasticsearch-lang-python/2.3.1/elasticsearch-lang-python-2.3.1.zip...
Trying https://github.com/elasticsearch/elasticsearch-lang-python/archive/2.3.1.zip...
Trying https://github.com/elasticsearch/elasticsearch-lang-python/archive/master.zip...
Downloading .......................DONE
Installed elasticsearch/elasticsearch-lang-python/2.3.1 into .../elasticsearch-1.3.7/plugins/lang-python
Usage:
    -u, --url     [plugin location]   : Set exact URL to download the plugin from
    -i, --install [plugin name]       : Downloads and installs listed plugins [*]
    -t, --timeout [duration]          : Timeout setting: 30s, 1m, 1h... (infinite by default)
    -r, --remove  [plugin name]       : Removes listed plugins
    -l, --list                        : List installed plugins
    -v, --verbose                     : Prints verbose messages
    -s, --silent                      : Run in silent mode
    -h, --help                        : Prints this help message

 [*] Plugin name could be:
     elasticsearch/plugin/version for official elasticsearch plugins (download from download.elasticsearch.org)
     groupId/artifactId/version   for community plugins (download from maven central or oss sonatype)
     username/repository          for site plugins (download from github master)

Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.
```

**Comment by beiske** [comment]
After giving this one a second look it appears the 2.3.1 release has not been published to download.elasticsearch.org like the other releases. I'm therefore able to work around the issue by changing the command to ```bin/plugin -install org.elasticsearch/elasticsearch-lang-python/2.3.1``` and then the pluginmanager downloads the release from maven central.

Any particular reason this release has not been published to elasticsearch.org like the others?

**Comment by dadoonet** [comment]
Where do you see that we released a 2.3.1 version? I can not see it on the README page here: https://github.com/elasticsearch/elasticsearch-lang-python

**Comment by dadoonet** [comment]
Hmmm. Forget my comment. I see. So you need a 2.3.1 version to be released?

**Comment by beiske** [comment]
I've worked around the issue, and changed our Jenkins build to use the releases from maven central, so no rush for me any more. I'm just curios if there is any particular reason the 2.3.1 release is not available in the same manner as the other releases. Did somebody just forget or has it not finished testing yet?

The README page should probably be updated too. The 2.3.1 version is only needed for 1.3.5 and later, but it looks like it is should be backwards compatible.

**Comment by dadoonet** [comment]
I think we just forgot to release it TBH :)

**Comment by dadoonet** [comment]
@beiske Sorry for the looooong delay it took. :(
I just released completely version 2.3.1 so it should work as any other release now.

I wonder how or why it was partially released (only on sonatype - no tag on github - nothing on elasticsearch download service). 

@tlrx sounds like you did it. Do you remember what happened? 
I released it again but I think I should now drop the staging repo on sonatype because it has been already published on Maven central.

**Comment by tlrx** [comment]
@dadoonet Not sure but I think the uploading of artefacts on Sonatype was stopped due to a server error. I checked the artefacts but maybe not everywhere.

**Comment by dadoonet** [comment]
Ok I released the sonatype staging repo to make sure everything is correct.
Do you remember if you hit the same issue for other repos?
